### ISSUE TITLE
Warning: Homepage URL matches documentation URL 

### ISSUE THREAD

**Issue by lanzone1** [cloudview-tech/google-tag-manager-event-code#1]
Hi,

When reviewing your template, we noticed that the homepage URL and the documentation URL are the same. Please either remove the documentation URL or set it to a different page.

Thanks.

**Comment by cloudview-tech** [comment]
Hi, @lanzone1 

We have add the documentation last week ([#e015181](https://github.com/cloudview-tech/google-tag-manager-event-code/commit/e0151819fbeb07549a22f9eeb4fde5d18520c7e9)), please reveiw the template again. Looking forward to your feedback.

Thanks.

**Comment by lanzone1** [comment]
Looks good. Expect your template to be approved shortly. Thanks!
